package net.volyera;

import java.util.List;

import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.item.enchantment.Enchantment;

/**
 * Typed references to the enchantments Volyera ships as data.
 *
 * <p>These are {@link ResourceKey}s, not registrations. Minecraft 26.2
 * enchantments are defined by datapack JSON - see
 * {@code data/volyera/enchantment} - and the game registers them itself.
 * The keys exist so that Java code, and other mods depending on Volyera,
 * can refer to a specific enchantment without repeating a string literal.
 *
 * <p>This file is generated by {@code tools/generate_enchantments.py} from the
 * same roster that produces the JSON. Do not edit it by hand; edit the tool.
 */
public final class VolyeraEnchantments {

    /** Any armour. Damage reduction plus armour toughness; protection family. */
    public static final ResourceKey<Enchantment> WARDING = key("warding");

    /** Any armour. Fire protection, shorter burns, ignites melee attackers. */
    public static final ResourceKey<Enchantment> EMBERHEART = key("emberheart");

    /** Any armour. Armour toughness and knockback resistance. */
    public static final ResourceKey<Enchantment> BULWARK = key("bulwark");

    /** Any armour. Bonus hearts, armour and knockback resistance. Rare. */
    public static final ResourceKey<Enchantment> COLOSSUS = key("colossus");

    /** Any armour. Freezing immunity and a chance to slow attackers. */
    public static final ResourceKey<Enchantment> GLACIAL_WARD = key("glacial_ward");

    /** Any armour. Lightning immunity; faster while a thunderstorm rages. */
    public static final ResourceKey<Enchantment> STORMWARDEN = key("stormwarden");

    /** Any armour. Periodic burst of regeneration. */
    public static final ResourceKey<Enchantment> REJUVENATION = key("rejuvenation");

    /** Any armour. Reflects thorns damage at melee attackers. */
    public static final ResourceKey<Enchantment> THORNMAIL = key("thornmail");

    /** Any armour. Luck, for better block and mob drops. */
    public static final ResourceKey<Enchantment> PROSPERITY = key("prosperity");

    /** Any armour. Treasure: toughness, knockback resistance, hearts, luck. */
    public static final ResourceKey<Enchantment> GILDED_AEGIS = key("gilded_aegis");

    /** Helmet. Drowning immunity, extra breath, faster swimming. */
    public static final ResourceKey<Enchantment> TIDEWARDEN = key("tidewarden");

    /** Helmet. Longer block and entity interaction range. */
    public static final ResourceKey<Enchantment> KEENEYE = key("keeneye");

    /** Leggings. Faster sneaking, ignores soul-sand-style slowdown. */
    public static final ResourceKey<Enchantment> SHADOWSTRIDE = key("shadowstride");

    /** Leggings. Speed bonus that builds once you are moving quickly. */
    public static final ResourceKey<Enchantment> MOMENTUM = key("momentum");

    /** Boots. Safer, softer and partly protected falls. */
    public static final ResourceKey<Enchantment> FEATHERSTEP = key("featherstep");

    /** Boots. Bounciness (new in 26.2), step height and jump strength. */
    public static final ResourceKey<Enchantment> SPRINGSTEP = key("springstep");

    /** Boots. Full swim speed and normal mining while submerged. */
    public static final ResourceKey<Enchantment> ABYSSWALKER = key("abysswalker");

    /** Chestplate. Bonus armour and a chance to weaken attackers. */
    public static final ResourceKey<Enchantment> VANGUARD = key("vanguard");

    /** Treasure curse. Slows you, weighs you down, cannot be removed. */
    public static final ResourceKey<Enchantment> CURSE_OF_ANCHORING = key("curse_of_anchoring");

    /** Treasure curse. Less toughness and steady durability drain. */
    public static final ResourceKey<Enchantment> CURSE_OF_FRAILTY = key("curse_of_frailty");

    /** Every enchantment Volyera defines, for iteration and sanity checks. */
    public static final List<ResourceKey<Enchantment>> ALL = List.of(
            WARDING,
            EMBERHEART,
            BULWARK,
            COLOSSUS,
            GLACIAL_WARD,
            STORMWARDEN,
            REJUVENATION,
            THORNMAIL,
            PROSPERITY,
            GILDED_AEGIS,
            TIDEWARDEN,
            KEENEYE,
            SHADOWSTRIDE,
            MOMENTUM,
            FEATHERSTEP,
            SPRINGSTEP,
            ABYSSWALKER,
            VANGUARD,
            CURSE_OF_ANCHORING,
            CURSE_OF_FRAILTY
    );

    private VolyeraEnchantments() {
    }

    private static ResourceKey<Enchantment> key(String path) {
        return ResourceKey.create(Registries.ENCHANTMENT, Volyera.id(path));
    }
}
